services:
  server:
    build: .
    ports:
      - 8080:8080
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=myStrong(!)Password
